data = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis consequat est. Aenean leo dui, mattis ut urna eget, pellentesque dapibus metus. Nunc mollis a erat et blandit. Proin vitae felis blandit, bibendum nulla lobortis, laoreet ex. Suspendisse venenatis lacus sed rhoncus ultricies. Praesent velit arcu, consectetur quis purus non, gravida elementum leo. Nulla at sodales erat. Praesent consequat sem in turpis congue, convallis feugiat metus euismod. Pellentesque nibh nibh, hendrerit sit amet arcu at, aliquam auctor velit. Etiam interdum dignissim leo, condimentum pretium nisl auctor quis. Vestibulum interdum volutpat posuere. Proin molestie finibus lorem vitae rutrum. Maecenas ac justo nec metus pharetra consectetur iaculis vulputate quam. Curabitur eu fermentum ante. Vivamus laoreet leo porta lacinia rhoncus. Vestibulum suscipit pretium risus, vitae viverra mauris ullamcorper et.",
        "Maecenas eu tristique libero. Fusce vel dolor ultrices, dapibus erat ut, aliquet sapien. Praesent iaculis nisl in leo egestas mattis. Aliquam aliquet consequat magna sit amet vehicula. Integer felis dolor, volutpat eget tellus quis, fermentum euismod ligula. Ut mattis tortor quis vestibulum rutrum. Mauris efficitur, mauris eget tempus dignissim, diam ante facilisis arcu, a ultrices lacus arcu vitae nisi. Donec molestie feugiat augue in semper. Nam ut convallis felis. Pellentesque nec massa quam. Donec placerat nisl eu turpis ornare pharetra vitae vitae massa. Vivamus convallis enim ac nunc imperdiet, sed aliquet lacus fringilla.",
        "Suspendisse vel fringilla odio, id elementum orci. Vivamus imperdiet ut sapien vel egestas. Morbi bibendum lobortis fermentum. Morbi malesuada tempor ipsum, rutrum sodales turpis facilisis quis. Vestibulum et aliquet turpis. Vivamus nec nisi vestibulum, sagittis augue sit amet, convallis quam. Fusce diam nibh, iaculis in mi eget, tempus pulvinar sem. Suspendisse eget arcu augue. Pellentesque id volutpat quam. Cras semper nisl vitae iaculis imperdiet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam at urna augue. Pellentesque vel lorem est.",
        "Morbi sollicitudin est sem, vitae convallis tortor commodo vitae. Nulla facilisi. Proin tellus lorem, lacinia ac felis et, rhoncus tincidunt ipsum. Phasellus lorem arcu, vestibulum vel erat a, ullamcorper imperdiet urna. Praesent vestibulum dignissim lorem, sit amet lacinia odio blandit tristique. Morbi blandit eros eu sem porta, eget tristique purus consequat. Duis et vehicula nunc. In hac habitasse platea dictumst. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam dapibus dolor placerat condimentum porttitor. Sed vulputate lorem at nisi facilisis, id commodo nibh sollicitudin. Nam blandit leo a elit commodo, sit amet mattis est venenatis. Integer luctus fringilla dolor, non interdum tellus sollicitudin a. Maecenas eget accumsan odio, sit amet consectetur velit.",
        "Integer egestas, mi eu commodo eleifend, leo mi varius sapien, eget eleifend felis risus posuere enim. Aliquam egestas est eu turpis tincidunt, nec mattis turpis finibus. Aliquam consectetur, eros ac tristique condimentum, elit nunc dapibus risus, eget mollis tortor diam vitae eros. Integer tincidunt blandit nulla, nec malesuada elit blandit vitae. Vivamus sit amet ante vel lacus pharetra aliquet. Phasellus malesuada bibendum scelerisque. Praesent eleifend quam id sapien sollicitudin, sit amet elementum tellus congue.",
        "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id quam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue. Proin sodales libero eget ante.",
        "Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam."
    ];


var input = document.getElementById("input");
var button = document.getElementById("btn");
var parag_box = document.getElementById("parag_box");

button.addEventListener("click", ()=>{
parag_box.innerHTML = "";
for(i = 0; i<+input.value; i++){
    var index = Math.floor(Math.random()*data.length);
    parag_box.innerHTML += `<div class="Paragraphs">
           ${data[index]}    
    </div>`
}
input.value = "";
})

